### ISSUE TITLE
Cannot successfully run `bundle exec rake issues:sync_collabs`

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-shipyard/ecosystem-dashboard#377]
Below is my attempt to run `bundle exec rake issues:sync_collabs --trace`. It points to https://github.com/ipfs-shipyard/ecosystem-dashboard/blob/018bf23d6cbce36f6fbe6d2a551e94517230c29e/app/models/repository.rb#L499

```bash
/usr/src/app # bundle exec rake issues:sync_collabs --trace
** Invoke issues:sync_collabs (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute issues:sync_collabs
rake aborted!
TypeError: no implicit conversion of nil into String
/usr/src/app/app/models/repository.rb:499:in `quote'
/usr/src/app/app/models/repository.rb:499:in `ecosystem_score_parts'
/usr/src/app/app/models/repository.rb:548:in `calculate_score'
/usr/src/app/app/models/repository.rb:557:in `update_score'
/usr/src/app/app/models/repository.rb:486:in `sync'
/usr/src/app/app/models/organization.rb:63:in `block in sync_recently_active_repos'
/usr/src/app/app/models/organization.rb:53:in `each'
/usr/src/app/app/models/organization.rb:53:in `sync_recently_active_repos'
/usr/local/bundle/gems/activerecord-7.0.2.2/lib/active_record/relation/delegation.rb:88:in `each'
/usr/local/bundle/gems/activerecord-7.0.2.2/lib/active_record/relation/delegation.rb:88:in `each'
/usr/src/app/lib/tasks/issues.rake:3:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/local/bundle/gems/bugsnag-6.24.2/lib/bugsnag/integrations/rake.rb:20:in `execute'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:25:in `load'
/usr/local/bundle/bin/rake:25:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
/usr/local/bundle/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => issues:sync_collabs
```

**Comment by andrew** [comment]
Pushed a fix for that, it looks like you haven't got `DISPLAY_NAME` or `DEFAULT_ORG` env vars set (recommend both set to `ipfs` in .env file). 

Also looks like you don't have any internal orgs, you should create a few in the rails console with `internal: true` for PL orgs like `ipfs`, `ipfs-shipyard`, `libp2p` etc
